
package com.irctc.reservation.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.irctc.reservation.wsdl.BusInfo;
import org.irctc.reservation.wsdl.PassengerInfo;
import org.irctc.reservation.wsdl.Ticket;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Reservation", targetNamespace = "http://irctc.org/reservation/wsdl")
@XmlSeeAlso({
    org.irctc.reservation.types.ObjectFactory.class,
    org.irctc.reservation.wsdl.ObjectFactory.class
})
public interface Reservation {


    /**
     * 
     * @param pInfo
     * @param bInfo
     * @return
     *     returns org.irctc.reservation.wsdl.Ticket
     */
    @WebMethod(action = "http://irctc.org/reservation/wsdl#doReservation")
    @WebResult(name = "result", targetNamespace = "http://irctc.org/reservation/types")
    @RequestWrapper(localName = "doReservation", targetNamespace = "http://irctc.org/reservation/wsdl", className = "org.irctc.reservation.wsdl.DoReservation")
    @ResponseWrapper(localName = "doReservationResponse", targetNamespace = "http://irctc.org/reservation/wsdl", className = "org.irctc.reservation.wsdl.DoReservationResponse")
    @Action(input = "http://irctc.org/reservation/wsdl#doReservation", output = "http://irctc.org/reservation/wsdl/Reservation/doReservationResponse")
    public Ticket doReservation(
        @WebParam(name = "bInfo", targetNamespace = "")
        BusInfo bInfo,
        @WebParam(name = "pInfo", targetNamespace = "http://irctc.org/reservation/types")
        PassengerInfo pInfo);

}
