
package com.irctc.reservation.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservationImplService", targetNamespace = "http://service.reservation.irctc.com/", wsdlLocation = "http://localhost:9090/SoapWebServiceApp/hello?wsdl")
public class ReservationImplService
    extends Service
{

    private final static URL RESERVATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVATIONIMPLSERVICE_EXCEPTION;
    private final static QName RESERVATIONIMPLSERVICE_QNAME = new QName("http://service.reservation.irctc.com/", "ReservationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/SoapWebServiceApp/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONIMPLSERVICE_WSDL_LOCATION = url;
        RESERVATIONIMPLSERVICE_EXCEPTION = e;
    }

    public ReservationImplService() {
        super(__getWsdlLocation(), RESERVATIONIMPLSERVICE_QNAME);
    }

    public ReservationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONIMPLSERVICE_QNAME, features);
    }

    public ReservationImplService(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONIMPLSERVICE_QNAME);
    }

    public ReservationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONIMPLSERVICE_QNAME, features);
    }

    public ReservationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationImplPort")
    public Reservation getReservationImplPort() {
        return super.getPort(new QName("http://service.reservation.irctc.com/", "ReservationImplPort"), Reservation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Reservation
     */
    @WebEndpoint(name = "ReservationImplPort")
    public Reservation getReservationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.reservation.irctc.com/", "ReservationImplPort"), Reservation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONIMPLSERVICE_EXCEPTION!= null) {
            throw RESERVATIONIMPLSERVICE_EXCEPTION;
        }
        return RESERVATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
